### PR TITLE
Update dues by  (except for student dues)

### PR DESCRIPTION
**Pull request by vdgsa-webcom-chair**
From Nancy: "The rates will be: $40 for individual and family memberships in the U.S., Canada, and the rest of North, Central, and South America; $45 for individual and family membership in all other countries; $45 for institutional memberships; and $20 for individuals with limited incomes, such as students."

### CODE REVIEW

**Comment by vdgsa-webcom-chair** [comment]
The old $35 dues are referenced in a few migrations files (such as `0005_auto_20201112_1453.py`), but those predate the global variables currently used now, so I assume they're obsolete.

**Comment by james-perretta** [comment]
You'll actually want to run `./manage.py makemigrations` and commit the new
migration file. This doesn't have any bearing on the database itself since
the only thing being changed is the display name for the choices, but if we
don't run makemigrations django will think that the migrations are out of
date.

Otherwise this looks fine. Doug, if you could take it for a spin on your
dev environment that would be much appreciated :)

**Comment by vdgsa-webcom-chair** [comment]
Doug or James, could you help me update the migrations?  I have to get my local venv working before I can run that command.

**Comment by ponticello** [comment]
Ok, I’ve created the migration file and checked it in to the pull request. I also had to update pipenv so I’ve checked the lock file in too. (Was that the right thing to do?)The change appears on the My account page as expected.I don’t have my stripe dev environment hooked up so when I submit I get an error. But I don’t think any of that has changed, so it should be ok.-Doug On Dec 27, 2023, at 1:42 PM, vdgsa-webcom-chair ***@***.***> wrote:﻿
Doug or James, could you help me update the migrations?  I have to get my local venv working before I can run that command.

**Comment by ponticello** [comment]
OK - sorry for the confusion. I rolled back the lock file - it should not be part of the pull request!
(FYI: I needed to do a pipenv install - not a pipenv update!)

I now go directly to stripe without any errors. We're good to go!

**Comment by vdgsa-webcom-chair** [comment]
> I now go directly to stripe without any errors. We're good to go!

Awesome - thank you Doug!  I can't approve as author, so could either James or you give it the stamp of approval?

I will plan to merge and deploy on the morning of the 31st (pacific time).

**Review by ponticello — APPROVED** [review]

**Pull request merged**
